// Legal Content Module
// Handles the rendering and processing of legal markdown content

/**
 * Initialize the legal content module
 */
export function initLegalContent() {
    loadLegalContent();
    addLegalContentEnhancements();
}

/**
 * Load all legal content into their respective modals
 */
function loadLegalContent() {
    // Terms of Service
    loadTermsOfService();
    
    // Privacy Policy
    loadPrivacyPolicy();
    
    // Imprint
    loadImprint();
}

/**
 * Add functional enhancements to legal content
 */
function addLegalContentEnhancements() {
    // Add table of contents to longer documents
    addTableOfContents(document.getElementById('termsModal'));
    addTableOfContents(document.getElementById('privacyModal'));
    
    // Add scroll to top button for longer documents
    addScrollToTopButton(document.getElementById('termsModal'));
    addScrollToTopButton(document.getElementById('privacyModal'));
}

/**
 * Load the Terms of Service content
 */
function loadTermsOfService() {
    const termsModal = document.getElementById('termsModal');
    if (!termsModal) return;
    
    const legalContent = termsModal.querySelector('.legal-content');
    if (!legalContent) return;
    
    // Replace placeholder with formatted content
    legalContent.innerHTML = formatTermsOfService();
}

/**
 * Load the Privacy Policy content
 */
function loadPrivacyPolicy() {
    const privacyModal = document.getElementById('privacyModal');
    if (!privacyModal) return;
    
    const legalContent = privacyModal.querySelector('.legal-content');
    if (!legalContent) return;
    
    // Replace placeholder with formatted content
    legalContent.innerHTML = formatPrivacyPolicy();
}

/**
 * Load the Imprint content
 */
function loadImprint() {
    const imprintModal = document.getElementById('imprintModal');
    if (!imprintModal) return;
    
    const legalContent = imprintModal.querySelector('.legal-content');
    if (!legalContent) return;
    
    // Replace placeholder with formatted content
    legalContent.innerHTML = formatImprint();
}

/**
 * Format the Terms of Service markdown into HTML
 * @returns {string} Formatted HTML content
 */
function formatTermsOfService() {
    return `
        <h1>Terms of Service for The Paper Mill</h1>
        <p>Last Updated: March 12, 2025</p>

        <h2>1. Introduction & Acceptance</h2>
        <p>These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and Querkauf UG ("Company," "we," "us," or "our") regarding your use of The Paper Mill website and services (collectively, the "Service"). By accessing or using our Service, you agree that you have read, understood, and agree to be bound by these Terms. If you disagree with any part of these Terms, you may not access the Service.</p>

        <h2>2. Eligibility</h2>
        <p>You must be at least 18 years old or have the legal capacity to enter into binding contracts under your jurisdiction's laws to use our Service. If you're under 18 but above the age of 13, you may use the Service only with the involvement and consent of a parent or legal guardian who agrees to be bound by these Terms.</p>

        <h2>3. Service Description</h2>
        <h3>3.1 The Paper Mill provides AI-powered academic paper generation based on user inputs.</h3>

        <h3>3.2 Service Limitations:</h3>
        <ul>
            <li>Theoretical papers only (no empirical research with original data)</li>
            <li>English-language papers</li>
            <li>Delivery in PDF and DOCX formats</li>
        </ul>

        <h3>3.3 While we strive to provide high-quality content, we do not guarantee that papers will:</h3>
        <ul>
            <li>Receive any specific grade or evaluation</li>
            <li>Be entirely free from errors or inaccuracies</li>
            <li>Be accepted by any academic institution</li>
        </ul>

        <h2>4. Academic Integrity Notice</h2>
        <h3>4.1 The Service is provided as a reference and research tool.</h3>

        <h3>4.2 You are solely responsible for how you use the papers generated by our Service. We explicitly discourage submitting our papers as your own work without proper attribution, modification, or your institution's permission.</h3>

        <h3>4.3 We accept no liability for academic, professional, or personal consequences resulting from your use of our Service, including but not limited to academic dishonesty proceedings, course failures, or academic dismissals.</h3>

        <h2>5. User Conduct & Restrictions</h2>
        <p>You agree not to use the Service to:</p>

        <h3>5.1 Generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable.</h3>

        <h3>5.2 Impersonate any person or entity or falsely state or misrepresent your affiliation.</h3>

        <h3>5.3 Engage in any activity that interferes with or disrupts the Service.</h3>

        <h3>5.4 Attempt to access any part of the Service, or any server, account, or database connected to the Service by hacking, password mining, or other illegitimate means.</h3>

        <h3>5.5 Use the Service for any commercial purpose without our express written permission.</h3>

        <h2>6. Payment Terms</h2>
        <h3>6.1 We offer a base price plus additional costs for specific options as described on our website.</h3>

        <h3>6.2 All payments are processed through Stripe. By providing payment information, you represent that you are authorized to use the payment method and agree to the terms of our payment processor.</h3>

        <h3>6.3 Prices displayed include applicable sales taxes, value-added taxes (VAT), or similar taxes required by law.</h3>

        <h3>6.4 Our service charges per paper with no recurring subscriptions.</h3>

        <h2>7. Refund Policy</h2>
        <h3>7.1 We will issue a full refund if your paper fails our internal quality standards (though you won't receive the subpar paper).</h3>

        <h3>7.2 Beyond quality failures, we don't offer revisions or refunds.</h3>

        <h3>7.3 If you believe your paper failed to meet our quality standards, contact us within 7 days of delivery with specific concerns.</h3>

        <h2>8. Intellectual Property</h2>
        <h3>8.1 The Service, including its design, features, content, and underlying technology, is owned by us and protected by copyright, trademark, and other intellectual property laws.</h3>

        <h3>8.2 Once delivered and payment is completed, the content of the generated paper belongs entirely to you.</h3>

        <h3>8.3 If you provide us with feedback or suggestions regarding our Service, you grant us a non-exclusive, royalty-free, perpetual, irrevocable license to use that feedback without restriction.</h3>

        <h2>9. Privacy & Data Handling</h2>
        <p>We handle your information as described in our Privacy Policy, which is incorporated into these Terms by reference. By using our Service, you consent to the collection and use of information as detailed in our Privacy Policy.</p>

        <h2>10. Limitation of Liability</h2>
        <h3>10.1 THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.</h3>

        <h3>10.2 TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM:</h3>
        <p>(a) YOUR USE OF OR INABILITY TO USE THE SERVICE;<br>
        (b) ANY CONTENT OBTAINED THROUGH THE SERVICE;<br>
        (c) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA.</p>

        <h3>10.3 IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE AMOUNT YOU PAID TO US FOR THE SERVICE DURING THE PAST THREE MONTHS.</h3>

        <h2>11. Indemnification</h2>
        <p>You agree to indemnify, defend, and hold harmless Querkauf UG and its officers, directors, employees, agents, and affiliates from any claims, liabilities, damages, losses, costs, or expenses, including reasonable attorneys' fees, arising out of or in any way connected with your access to or use of the Service or your violation of these Terms.</p>

        <h2>12. Term & Termination</h2>
        <h3>12.1 These Terms shall remain in full force and effect while you use the Service.</h3>

        <h3>12.2 We may suspend or terminate your access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason.</h3>

        <h3>12.3 Upon termination, your access to the Service will cease immediately.</h3>

        <h2>13. Changes to Terms</h2>
        <p>We may modify these Terms at any time by posting the revised terms on our website. Your continued use of the Service after such changes constitutes your acceptance of the new Terms.</p>

        <h2>14. Governing Law & Dispute Resolution</h2>
        <h3>14.1 These Terms shall be governed by and construed in accordance with the laws of Germany, without regard to its conflict of law principles.</h3>

        <h3>14.2 Any dispute arising out of or relating to these Terms or the Service shall be subject to the exclusive jurisdiction of the courts of Ulm, Germany (Amtsgericht Ulm).</h3>

        <h3>14.3 You may only resolve disputes with us on an individual basis and may not bring a claim as a plaintiff or class member in a class, consolidated, or representative action.</h3>

        <h2>15. General Provisions</h2>
        <h3>15.1 These Terms constitute the entire agreement between you and us regarding the Service and supersede all prior agreements and understandings.</h3>

        <h3>15.2 If any provision of these Terms is found to be unenforceable, that provision shall be enforced to the maximum extent possible, and the remaining provisions shall remain in full force and effect.</h3>

        <h3>15.3 Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.</h3>

        <h3>15.4 You may not assign or transfer these Terms without our prior written consent, but we may assign these Terms without restriction.</h3>

        <h3>15.5 We shall not be liable for any failure to perform our obligations if such failure is a result of acts of nature, fire, flood, earthquake, terrorist attack, internet service provider failure, labor dispute, or other causes beyond our reasonable control.</h3>

        <h2>16. Contact Information</h2>
        <p>If you have any questions about these Terms, please contact us at:</p>

        <p>Querkauf UG<br>
        Ellerbachweg 40<br>
        89079 Ulm, Germany<br>
        Email: info@papermill.fun</p>

        <hr>

        <p>These Terms are effective as of March 12, 2025, and were last updated on the same date.</p>
    `;
}

/**
 * Format the Privacy Policy markdown into HTML
 * @returns {string} Formatted HTML content
 */
function formatPrivacyPolicy() {
    return `
        <h1>Privacy Policy for The Paper Mill</h1>
        <p>Last Updated: March 12, 2025</p>

        <h2>1. Introduction</h2>
        <p>This Privacy Policy describes how Querkauf UG ("we," "us," or "our") collects, uses, and discloses your information when you use our website (https://papermill.fun) and services (collectively, the "Services").</p>

        <h2>2. Information We Collect</h2>
        <h3>2.1 Information You Provide</h3>
        <ul>
            <li>Paper topic, academic discipline, selected options, and specific requirements</li>
            <li>Payment information (processed by Stripe)</li>
            <li>Communications with us</li>
        </ul>

        <h3>2.2 Information Automatically Collected</h3>
        <ul>
            <li>Usage data (IP address, browser type, operating system, referring pages, access times)</li>
            <li>Device information</li>
            <li>Cookies and similar technologies</li>
            <li>General location derived from IP address</li>
        </ul>

        <h2>3. How We Use Your Information</h2>
        <p>We use your information to:</p>
        <ul>
            <li>Provide and maintain our Services</li>
            <li>Process payments and send invoices</li>
            <li>Improve and optimize our Services</li>
            <li>Communicate with you about your orders</li>
            <li>Provide customer support</li>
            <li>Prevent fraud and enforce our Terms of Service</li>
            <li>Comply with legal obligations</li>
        </ul>

        <h2>4. Legal Basis for Processing (GDPR)</h2>
        <p>Under the General Data Protection Regulation (GDPR), we process your personal data based on:</p>
        <ul>
            <li>Performance of a contract</li>
            <li>Legitimate interests</li>
            <li>Consent</li>
            <li>Legal obligation</li>
        </ul>

        <h2>5. Information Sharing and Disclosure</h2>
        <h3>5.1 Service Providers</h3>
        <p>We share information with:</p>
        <ul>
            <li>Stripe (payment processing)</li>
            <li>Anthropic (Claude), OpenAI (ChatGPT), xAI (Grok), and DeepSeek (AI services)</li>
            <li>SendGrid (email services)</li>
            <li>Google Analytics and Meta Analytics (analytics)</li>
        </ul>

        <h3>5.2 Legal Requirements</h3>
        <p>We may disclose information if required by law, regulation, legal process, or governmental request.</p>

        <h3>5.3 Business Transfers</h3>
        <p>In the event of a merger, acquisition, or sale of all or part of our assets, user information may be transferred as part of the transaction.</p>

        <h2>6. Cookies and Tracking Technologies</h2>
        <p>We use cookies and similar technologies to:</p>
        <ul>
            <li>Remember your preferences</li>
            <li>Analyze how you use our website</li>
            <li>Measure the effectiveness of our marketing</li>
        </ul>
        <p>Most browsers allow you to control cookies through their settings. Refusing cookies may impact your experience.</p>

        <h2>7. Data Retention</h2>
        <p>We retain your information only as long as necessary:</p>
        <ul>
            <li>Paper content and order information is automatically purged from our systems one month after delivery</li>
            <li>Payment information is retained as required for accounting and tax purposes</li>
        </ul>

        <h2>8. Data Security</h2>
        <p>We implement appropriate security measures to protect your information. However, no method of transmission over the Internet or electronic storage is 100% secure.</p>

        <h2>9. Your Rights (GDPR)</h2>
        <p>Under the GDPR, you have rights regarding your personal data:</p>
        <ul>
            <li>Right to access</li>
            <li>Right to rectification</li>
            <li>Right to erasure</li>
            <li>Right to restrict processing</li>
            <li>Right to data portability</li>
            <li>Right to object</li>
            <li>Rights regarding automated decision-making</li>
            <li>Right to withdraw consent</li>
        </ul>
        <p>To exercise these rights, contact us at info@papermill.fun.</p>

        <h2>10. International Data Transfers</h2>
        <p>When we transfer data outside the European Economic Area (EEA), we ensure appropriate safeguards through:</p>
        <ul>
            <li>EU Standard Contractual Clauses</li>
            <li>Adequacy decisions by the European Commission</li>
            <li>Privacy Shield certification (where applicable)</li>
            <li>Obtaining your consent for specific transfers</li>
        </ul>

        <h2>11. Children's Privacy</h2>
        <p>Our Services are not intended for individuals under 13 years of age. We do not knowingly collect personal information from children under 13.</p>

        <h2>12. Changes to This Privacy Policy</h2>
        <p>We may update this Privacy Policy from time to time. The revised policy will be posted on our website with an updated effective date.</p>

        <h2>13. Third-Party Links</h2>
        <p>Our website may contain links to third-party websites that are not operated by us. We have no control over and assume no responsibility for these websites' content, privacy policies, or practices.</p>

        <h2>14. Contact Information</h2>
        <p>Querkauf UG<br>
        Attn: Data Protection Officer (Robert Bernhardt)<br>
        Ellerbachweg 40<br>
        89079 Ulm, Germany<br>
        Email: info@papermill.fun</p>

        <h2>15. Complaints</h2>
        <p>If you believe your data protection rights have been infringed, you have the right to lodge a complaint with a supervisory authority in the EU member state of your residence, place of work, or place of the alleged infringement.</p>

        <hr>

        <p>This Privacy Policy is effective as of March 12, 2025, and was last updated on the same date.</p>
    `;
}

/**
 * Format the Imprint markdown into HTML
 * @returns {string} Formatted HTML content
 */
function formatImprint() {
    return `
        <h1>Imprint (Impressum)</h1>
        <p>According to § 5 TMG (German Telemedia Act)</p>

        <h2>Company Information</h2>
        <p>Company Name:<br>
        Querkauf UG (haftungsbeschränkt)</p>

        <p>Address:<br>
        Ellerbachweg 40<br>
        89079 Ulm<br>
        Germany</p>

        <p>Managing Director (Geschäftsführer):<br>
        Robert Bernhardt</p>

        <p>Registration:<br>
        Amtsgericht Ulm, HRB 741050</p>

        <p>VAT ID:<br>
        DE313491043</p>

        <p>Tax ID:<br>
        88003/72666</p>

        <h2>Contact</h2>
        <p>Email: info@papermill.fun</p>

        <h2>Responsible for Content (§ 55 Abs. 2 RStV)</h2>
        <p>Robert Bernhardt<br>
        Ellerbachweg 40<br>
        89079 Ulm<br>
        Germany</p>

        <h2>Online Dispute Resolution</h2>
        <p>The European Commission provides a platform for online dispute resolution (OS): <a href="https://ec.europa.eu/consumers/odr/" target="_blank" rel="noopener noreferrer">https://ec.europa.eu/consumers/odr/</a></p>

        <p>We are not willing or obliged to participate in dispute resolution proceedings before a consumer arbitration board.</p>

        <hr>

        <p>Last updated: March 12, 2025</p>
    `;
}

/**
 * Add a table of contents to a modal
 * @param {HTMLElement} modal - The modal element to add the TOC to
 */
function addTableOfContents(modal) {
    if (!modal) return;
    
    const legalContent = modal.querySelector('.legal-content');
    if (!legalContent) return;
    
    // Get all h2 elements from the content
    const headings = legalContent.querySelectorAll('h2');
    if (headings.length < 3) return; // Only add TOC for documents with enough sections
    
    // Create TOC container
    const tocContainer = document.createElement('div');
    tocContainer.className = 'legal-toc';
    tocContainer.innerHTML = '<p><strong>Contents:</strong></p>';
    
    // Create TOC list
    const tocList = document.createElement('ul');
    tocContainer.appendChild(tocList);
    
    // Add headings to TOC
    headings.forEach((heading, index) => {
        // Add ID to heading if it doesn't have one
        if (!heading.id) {
            heading.id = `section-${index + 1}`;
        }
        
        // Create list item
        const listItem = document.createElement('li');
        const link = document.createElement('a');
        link.href = `#${heading.id}`;
        link.textContent = heading.textContent;
        link.addEventListener('click', function(e) {
            e.preventDefault();
            
            // Smooth scroll to section
            const target = document.getElementById(heading.id);
            if (!target) return;
            
            const modalBody = modal.querySelector('.modal-body');
            if (!modalBody) return;
            
            // Account for heading position inside scrollable container
            modalBody.scrollTo({
                top: target.offsetTop - 20,
                behavior: 'smooth'
            });
        });
        
        listItem.appendChild(link);
        tocList.appendChild(listItem);
    });
    
    // Insert TOC at the beginning of the content
    const firstHeading = legalContent.querySelector('h1');
    if (firstHeading && firstHeading.nextElementSibling) {
        legalContent.insertBefore(tocContainer, firstHeading.nextElementSibling.nextElementSibling);
    } else {
        legalContent.insertBefore(tocContainer, legalContent.firstChild);
    }
}

/**
 * Add a scroll to top button to a modal
 * @param {HTMLElement} modal - The modal element to add the button to
 */
function addScrollToTopButton(modal) {
    if (!modal) return;
    
    const modalBody = modal.querySelector('.modal-body');
    if (!modalBody) return;
    
    // Create scroll to top button
    const scrollButton = document.createElement('button');
    scrollButton.className = 'scroll-to-top';
    scrollButton.innerHTML = '↑';
    scrollButton.setAttribute('aria-label', 'Scroll to top');
    scrollButton.setAttribute('title', 'Scroll to top');
    
    // Add button to modal
    modalBody.appendChild(scrollButton);
    
    // Initial state - hidden
    scrollButton.style.display = 'none';
    
    // Show/hide button based on scroll position
    modalBody.addEventListener('scroll', function() {
        if (modalBody.scrollTop > 300) {
            scrollButton.style.display = 'block';
        } else {
            scrollButton.style.display = 'none';
        }
    });
    
    // Scroll to top when button is clicked
    scrollButton.addEventListener('click', function() {
        modalBody.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    });
}