// Example Content Module
// Provides content and data for academic paper examples

/**
 * Get all examples data
 * @returns {Array} Array of example objects
 */
export function getAllExamples() {
    return [
        // These are the examples that will be loaded when clicking "View More Examples"
        {
            id: 'pizza-economics',
            title: 'The Economics of Pizza Toppings: A Cost-Benefit Analysis of Pineapple as a Divisive Market Resource',
            field: 'Economics',
            type: 'Seminar Paper',
            excerpt: 'This groundbreaking economic analysis examines the contentious market dynamics of pineapple as a pizza topping, quantifying both monetary and social costs against perceived taste benefits. Through robust statistical modeling and controlled taste studies, we demonstrate that the pineapple-on-pizza debate represents a microcosm of broader market preference divergence patterns',
            score: 8.7,
            abstract: 'This paper applies microeconomic analysis to the controversial practice of adding pineapple to pizza. Using data from 250 pizzerias across North America and Europe, we calculate the economic surplus generated by pineapple as a pizza topping while accounting for negative externalities including social discord and dining compatibility constraints. Our hedonic pricing model reveals a bifurcated market with price elasticity varying significantly between preference groups. The findings suggest that taste polarization creates market inefficiencies that could be mitigated through sectional topping distribution strategies and personalized marketing approaches.',
            content: 'Note: Full paper content would appear here.',
            isInitial: false
        },
        {
            id: 'emoji-hieroglyphics',
            title: 'Emoji as Modern Hieroglyphics: A Comparative Analysis of Ancient Egyptian Writing Systems and Contemporary Digital Communication',
            field: 'Literature',
            type: 'Academic Paper',
            excerpt: 'This comparative linguistic study systematically analyzes structural parallels between Ancient Egyptian hieroglyphics and modern emoji-based communication. By examining ideographic principles, semantic evolution, and contextual dependencies across both systems, we demonstrate that emoji usage follows similar developmental patterns to early writing systems',
            score: 9.3,
            abstract: 'This paper presents a systematic comparison between Ancient Egyptian hieroglyphics and contemporary emoji usage in digital communication. Through analysis of semantic evolution, combinatorial patterns, and contextual interpretation requirements, we identify striking structural similarities between these systems separated by over 5,000 years. Our corpus analysis of 30,000 social media posts reveals that emoji increasingly function as logographic elements rather than mere emotional indicators, following a developmental trajectory parallel to ancient writing systems. The research demonstrates how technological constraints shape the evolution of visual communication regardless of historical period.',
            content: 'Note: Full paper content would appear here.',
            isInitial: false
        },
        {
            id: 'pillow-forts',
            title: 'The Ergonomics of Pillow Forts: Structural Integrity and Comfort Optimization in Temporary Domestic Constructions',
            field: 'Architecture',
            type: 'Bachelor Thesis',
            excerpt: 'This architectural analysis applies structural engineering principles to the common childhood practice of constructing pillow forts. Through systematic testing of materials, configurations, and environmental variables, we establish optimal building strategies that maximize both structural integrity and occupant comfort',
            score: 8.9,
            abstract: 'This thesis examines the architectural principles underlying successful pillow fort construction in domestic environments. Through iterative testing of 24 distinct structural configurations using common household materials, we establish quantitative metrics for stability, comfort, and spatial efficiency. Our research identifies the critical importance of proper foundation-to-height ratios and the strategic deployment of tensile elements (blankets) in creating resilient temporary structures. The findings are synthesized into a comprehensive design framework applicable to both recreational fort building and emergency shelter construction using minimal household resources.',
            content: 'Note: Full paper content would appear here.',
            isInitial: false
        },
        {
            id: 'meme-evolution',
            title: 'Meme Evolution and Social Cohesion: How Internet Humor Creates Generational Identity Markers',
            field: 'Sociology',
            type: 'PhD Thesis',
            excerpt: 'This longitudinal study traces the evolution of internet memes as social artifacts that define generational boundaries and establish group identity. By documenting transmission patterns, reference mutations, and comprehension thresholds across demographic groups, we demonstrate how shared humor creates powerful in-group dynamics',
            score: 9.6,
            abstract: 'This dissertation investigates how internet memes function as social artifacts that define generational boundaries and reinforce group identity. Through a five-year longitudinal study of meme transmission patterns across digital platforms, we document how reference comprehension creates distinct social demarcations between demographic cohorts. Our analysis of 15,000 meme variations demonstrates that humor based on shared cultural knowledge serves as a powerful mechanism for in-group identification and out-group differentiation. The research suggests that meme literacy functions as a form of cultural capital that defines digital native generations more distinctly than traditional demographic markers.',
            content: 'Note: Full paper content would appear here.',
            isInitial: false
        },
        {
            id: 'playground-governance',
            title: 'Governance Systems of Playground Hierarchies: Power Dynamics and Policy Formation Among Children Fighting for Swing Access',
            field: 'Political Science',
            type: 'Master Thesis',
            excerpt: 'This political microanalysis examines the emergent governance structures that develop on elementary school playgrounds, with particular focus on resource allocation conflicts surrounding high-demand equipment. Through field observation and controlled experiments, we document how children spontaneously develop complex regulatory systems',
            score: 9.1,
            abstract: 'This thesis examines the spontaneous formation of governance structures among children competing for limited playground resources. Based on 200 hours of field observation at 12 elementary schools, we document how children aged 6-11 develop sophisticated systems for managing conflicts over high-demand equipment such as swings and slides. Our analysis reveals striking parallels to canonical political theory, with playground communities demonstrating forms of direct democracy, authoritarian leadership, and even constitutional systems with established norms for succession and resource allocation. The findings suggest that fundamental patterns of human governance emerge naturally in miniature societies facing resource scarcity, regardless of formal political education.',
            content: 'Note: Full paper content would appear here.',
            isInitial: false
        },
        {
            id: 'recursive-procrastination',
            title: 'Recursive Procrastination: A New Sorting Algorithm Based on Deadline Proximity and Panic-Driven Efficiency',
            field: 'Computer Science',
            type: 'Academic Paper',
            excerpt: 'This computational analysis introduces a novel sorting algorithm inspired by human procrastination patterns, which paradoxically achieves peak efficiency under extreme deadline constraints. Through benchmarking against established algorithms, we demonstrate superior performance in specific high-pressure scenarios',
            score: 9.4,
            abstract: 'This paper introduces and validates a novel sorting algorithm inspired by observed patterns in human task prioritization under deadline pressure. The Recursive Procrastination Algorithm (RPA) deliberately delays sorting operations until time constraints reach critical thresholds, at which point it implements a highly parallelized processing approach. Our benchmark testing against established algorithms demonstrates that RPA outperforms traditional methods by up to 28% in scenarios with dynamically shifting priorities and limited processing windows. The algorithm\'s efficiency correlates inversely with available time, mirroring the paradoxical human tendency toward heightened productivity under extreme deadline pressure.',
            content: 'Note: Full paper content would appear here.',
            isInitial: false
        }
    ];
}

/**
 * Get example data by ID
 * @param {string} id - The example ID
 * @returns {Object|null} The example object or null if not found
 */
export function getExampleById(id) {
    const examples = getAllExamples();
    return examples.find(example => example.id === id) || null;
}

/**
 * Get all initial examples (those already on the page)
 * @returns {Array} Array of initial example objects
 */
export function getInitialExamples() {
    const examples = getAllExamples();
    return examples.filter(example => example.isInitial);
}

/**
 * Get additional examples (those to be loaded on button click)
 * @param {number} count - The number of examples to get (default: all additional)
 * @returns {Array} Array of additional example objects
 */
export function getAdditionalExamples(count = 0) {
    const examples = getAllExamples();
    const additionalExamples = examples.filter(example => !example.isInitial);
    
    if (count > 0 && count < additionalExamples.length) {
        return additionalExamples.slice(0, count);
    }
    
    return additionalExamples;
}